Corrected CI securtiy syntax

diff --git a/.github/workflows/ci-security.yml b/.github/workflows/ci-security.yml
--- a/.github/workflows/ci-security.yml
+++ b/.github/workflows/ci-security.yml
@@ -46,6 +46,7 @@ jobs:
         run: pip install semgrep
 
       - name: Run Semgrep SAST
+        id: semgrep
         run: semgrep --config auto --error
         continue-on-error: true
 
@@ -61,6 +62,7 @@ jobs:
           chmod +x /usr/local/bin/gitleaks
 
       - name: Run Gitleaks
+        id: gitleaks
         run: gitleaks detect --redact --source .
         continue-on-error: true
 
@@ -78,6 +80,7 @@ jobs:
 
       # SCA for whole repo (Python + React)
       - name: Trivy filesystem scan
+        id: trivy_fs
         run: trivy fs --exit-code 1 --severity HIGH,CRITICAL .
         continue-on-error: true
 
@@ -97,12 +100,10 @@ jobs:
               echo "No IaC files found, skipping IaC scan."
           fi
         continue-on-error: true
-      
+        id: trivy_iac
+
       - name: Fail pipeline if any security scan failed
-      if: ${{steps.semgrep.outcome == 'failure' || steps.gitleaks.outcome == 'failure' || steps.trivy.outcome == 'failure'}}
-      run: |
-        echo "One or more security scans failed – marking pipeline as failed."
-        exit 1
-      
-      
-    
+        if: ${{ steps.semgrep.outcome == 'failure' || steps.gitleaks.outcome == 'failure' || steps.trivy_fs.outcome == 'failure' || steps.trivy_iac.outcome == 'failure' }}
+        run: |
+          echo "One or more security scans failed – marking pipeline as failed."
+          exit 1
